# configuration.nix
{ config, pkgs, ... }:

{
  # The hardware configuration should be automatically generated by disko
  imports = [];

  # Bootloader Configuration (Required for UEFI systems)
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Enable all hardware firmware (will probably require unfree)
  hardware.enableAllFirmware = true;

  # Networking & Wi-Fi
  networking.hostName = "nixos"; # Define default hostname
  networking.networkmanager = {
    enable = true;
    wifi.backend = "iwd";
  };

  # Enable flake usage
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  # Localization & Time Zone
  time.timeZone = "Europe/London";
  i18n.defaultLocale = "en_GB.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_GB.UTF-8";
    LC_IDENTIFICATION = "en_GB.UTF-8";
    LC_MEASUREMENT = "en_GB.UTF-8";
    LC_MONETARY = "en_GB.UTF-8";
    LC_NAME = "en_GB.UTF-8";
    LC_NUMERIC = "en_GB.UTF-8";
    LC_PAPER = "en_GB.UTF-8";
    LC_TELEPHONE = "en_GB.UTF-8";
    LC_TIME = "en_GB.UTF-8";
  };

  # Audio via PipeWire
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    jack.enable = true;
  };

  # System packages available to all users
  environment.systemPackages = with pkgs; [
    git
    vim
    wget
    curl
    firefox
    networkmanagerapplet
  ];

  # Compatibility state version (Do not change unless upgrading across major releases)
  system.stateVersion = "unstable";
}
